server:
  port: 8080

spring:
  application:
    name: GreenCup

  datasource:
    url: jdbc:mysql://localhost:3306/mydb  # Replace with your database name
    username: dev                    # Replace with your MySQL username
    password: 1234                   # Replace with your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # Adjust based on your MySQL version

frontend:
  url: http://localhost:5173